# COMP-240 Homework 2

This homework assignment includes two exercises with simple coding tasks to help you familiarize with array-oriented programming through the use of the most popular python library, namely [NumPy](http://numpy.org).

Before we start you need to have installed in your python environment NumPy and of course jupyter notebooks. If you have downloaded and installed anaconda with all libraries pre-downloaded then you do not need to do anything else. To check just run the below cell and see if you get an error message. 

If you have downloaded anaconda but did not pre-download any libraries then open a terminal (e.g., for windows open command prompt) and download NumPy via the conda package manager:

```python
conda install numpy
```

First... let's import to the notebook NumPy by just running the below cell:

In [ ]:
import numpy as np

## Exercise 1

Show the contents of the array below:

In [ ]:
arr1 = np.arange(20)
arr1

Create a new array from arr1, named arr2, which has in odd indexed positions -1:

In [ ]:
#your code goes here
arr2 = arr1.copy()
arr2[1::2] = -1
arr2

Create a new array, named arr3, that only holds the common elements that are indexed in the same position:

In [ ]:
#your code goes here
arr3 = np.where(arr1 == arr2)
arr3

Create a new array, named arr4, that holds the elements of arr2 but is a 4x5 array:

In [ ]:
#your code goes here
arr4 = arr2.copy()
arr4 = arr4.reshape((4, 5))
arr4

Create a 1d vector, named v1, from arr4 that holds the values of the 3rd column:

In [ ]:
#your code goes here
v1 = arr4[:, 2:3]
np.concatenate(v1)

Create a new array, named arr5, from arr4 that holds the values from row 2 to 3 and columns 2 to 4:

In [ ]:
#your code goes here
arr5 = arr4[1:3, 1:4].copy()
arr5

Replace in arr5 the -1 elements with 42. Print arr5 and arr4. If you have corretly created arr5 from arr4, then arr4 should not have been altered:

In [ ]:
#your code goes here
arr5[arr5 == -1] = 42
print(f'arr4:\n {arr4}')
print(f'arr5:\n {arr5}')

Replace now in arr4 the -1 elements in row2 with 42 and in row 3 with 50:

In [ ]:
#your code goes here
arr4[1:2, :][arr4[1:2, :] == -1] = 42
arr4[2:3, :][(arr4[2:3, :]) == -1] = 50
arr4

Compute the sum and mean of all the values in arr4:

In [ ]:
#your code goes here
print(f'Sum of arr4: {np.sum(arr4)}')
print(f'Mean of arr4: {np.mean(arr4)}')

Compute the sum and mean of each column in arr4:

In [ ]:
#your code goes here
print(f'Sum of each column:\n {np.sum(arr4, axis=0)}')
print(f'Mean of each column:\n {np.mean(arr4, axis=0)}')

Compute the mean of the mean of each column in arr4:

In [ ]:
#your code goes here
print(f'Mean of mean of each column: {np.mean(np.mean(arr4, axis=0))}')

Create a python function which normalizes a float number given the min and max. Next, vectorize this function so it can be used by numpy for fast element-wise computations.

hint normalization means: 
$$
normalized\_num = (num - min) / (max - min)
$$

Afterwards, create a randomly filled 4x4 matrix, named rarr, and then normalize it:

In [ ]:
#your code goes here
def normalize(num, min, max):
    return (num - min) / (max - min)

normalize_vectorize = np.vectorize(normalize, otypes=[float])

In [ ]:
rarr = np.random.rand(4, 4)
print(f'Random 4x4 array:\n {rarr}')
print(f'Normalized array:\n {normalize_vectorize(rarr, np.min(rarr), np.max(rarr))}')

## Exercise 2

For this exercise we will use one of the most popular machine-learning datasets called the "iris" flower dataset.

How the dataset is accessed and converted to a numpy array will be thoroughly explained in follow-up lectures.

In [ ]:
iris_url = 'https://dl.dropboxusercontent.com/s/pk0khqy3iiwqy21/iris.data?dl=0'
iris = np.genfromtxt(iris_url, delimiter = ',', dtype = float)

names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

iris2 = iris[:, :4].copy()
iris2[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

iris3 = iris[:, :4].copy()
iris3[np.random.randint(150, size=8)] = 0.0

print(iris[:5])

Print how many rows are in the **iris** dataset:

In [ ]:
#your code goes here
print(len(iris))
print(np.shape(iris)[0])

Drop the 5th column of the **iris** which contains nan values:

In [ ]:
#your code goes here
iris_without_nan = np.delete(iris, 4, axis=1)
iris_without_nan[:5]

Print the mean and standard deviation of the 1st and 2nd column of the **iris** datataset:

In [ ]:
#your code goes here
print(f'1st column Mean: {np.mean(iris_without_nan[:, 0])}')
print(f'2nd column Mean: {np.mean(iris_without_nan[:, 1])}')
print(f'1st column Std: {np.std(iris_without_nan[:, 0])}')
print(f'2nd column Std: {np.std(iris_without_nan[:, 1])}')

Filter the rows of the **iris** dataset that have petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0 and then print these rows:

In [ ]:
#your code goes here
filter = (iris_without_nan[:, 2] > 1.5) & (iris_without_nan[:, 0] < 5.0)
print(iris_without_nan[filter])

Drop the rows in the **iris2** dataset that have any missing values, how many rows are left:

In [30]:
#your code goes here
print(f'Original iris2:\n {iris2[10:15]}')
iris2_without_nan = iris2[~np.isnan(iris2).any(axis=1)]
print(f'\n Iris2 without NaN:\n {iris2_without_nan[10:15]}')

Original iris2:
 [[5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 nan]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]]

 Iris2 without NaN:
 [[5.4 3.7 1.5 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]]


In the **iris2** dataset replace all values below 1.0 with 1.0 and all values above 5.0 with 5.0:

In [31]:
#your code goes here
iris2_without_nan[(iris2_without_nan < 1.0)] = 1
iris2_without_nan[(iris2_without_nan > 5.0)] = 5
print(f'New iris2: \n {iris2_without_nan[10:15]}')

New iris2: 
 [[5.  3.7 1.5 1. ]
 [4.8 3.  1.4 1. ]
 [4.3 3.  1.1 1. ]
 [5.  4.  1.2 1. ]
 [5.  4.4 1.5 1. ]]


Compute the sum per row in the **iris2** dataset and then find the maximum row sum:


In [32]:
#your code goes here
sum_row = np.sum(iris2_without_nan, axis=1)
print(np.max(sum_row))

16.0


Find the max value per row and then find the min of all max-es:

In [33]:
#your code goes here
max_row = np.max(iris2_without_nan, axis=1)
print(np.min(max_row))

4.3


Remove from the **iris3** array the rows where all elements are 0.0.

In [34]:
#your code goes here
print(f'Original array:\n {iris3[39:47]}')

iris3_del = iris3[~np.all(iris3, axis=1) == 0]
print(f'\n New array:\n {iris3_del[39:47]}')

Original array:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [0.  0.  0.  0. ]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [0.  0.  0.  0. ]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 